type: Organization
headline: DUAS Americas Inc is an American Technology company based in Denver, Colorado, USA.
description: DUAS Americas Inc is an American Technology company based in Denver, Colorado, USA.
url: "http://duasamericasgroup.com"
logo: "images/logo-grey.png"
image: "images/logo-grey.png"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://duasamericasgroup.com" # the base hostname & protocol for your site
social: 
  name: "DUAS AMERICAS INC | DENVER, COLORADO"
  link: "https://www.facebook.com/duasamericasgroup"
google_site_verification: google39cf25423549c9c.html

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/duasamericasgroup
  - title: twitter
    url: https://twitter.com/duasamericasgroup
  - title: instagram
    url: https://instagram.com/duasamericasgroup
permalink: pretty
# Site settings
title: DUAS Americas Inc
email: corporate@duasamericasgroup.com
twitter_username: duasamericasgroup
github_username:  aslanvaroqua
# Build settings
markdown: kramdown
# paginate: 4
# paginate_path: "blog/page:num"
