# Site settings
title: DUAS @mericas Inc
email: corporate@DUASamericasgroup.com
description: > # this means to ignore newlines until "baseurl:"
  DUAS @mericas Group is an American multinational corporation that provides
  technology consulting, information & network security services, and enterprise software solutions. 
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: DUASamericasgroup
github_username:  aslanvaroqua

# Build settings
markdown: kramdown

# paginate: 4
# paginate_path: "blog/page:num"
