# Site settings
title: Meuse
email: corporate@duasamericasgroup.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://aslanvaroqua.github.io/duasamericasgroup" # the base hostname & protocol for your site
twitter_username: duasamericasgrouo
github_username:  duasamericasgroup

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "blog/page:num"


theme: jekyll-theme-minimal