# Site settings
title: DUAS Americas Group Inc
email: corporate@duasamericasgroup.com
description: > # this means to ignore newlines until "baseurl:"
  DUAS Americas Group is an American multinational corporation the provides
  business consulting, software solutions, network & information security,
  and other related services.  
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: duasamericasgroup
github_username:  aslanvaroqua

# Build settings
markdown: kramdown

# paginate: 4
# paginate_path: "blog/page:num"
